[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "rbgame"
authors = [{name = "Nguyen Thanh Trung", email = "nguyenthanhtrung291099@gmail.com"}]
dynamic = ["version", "description"]