env:
  colors_map: assets/csv_files/colors_map.csv
  targets_map: assets/csv_files/targets_map.csv
  required_mail: 4
  robot_colors: 
    - r
    - b
  num_robots_per_player: 1
  with_battery: false
  random_num_steps: false
  max_step: 500

agent1:
  count: 1
  agent_class: src.agents.dqn_agent.DQNAgent
  model_class: tianshou.utils.net.common.Net
  model_args:
    state_shape: 6
    action_shape: 5
    hidden_sizes: [512, 512 ,256, 256, 128, 128, 64, 64]
    norm_layer: torch.nn.LayerNorm
    device: cpu
    dueling_param:
      - {}
      - {}
  policy_class: tianshou.policy.DQNPolicy
  policy_args:
    discount_factor: 0.99
    estimation_step: 30
    target_update_freq: 500
    is_double: true
  update_per_step: 0.05
  learning_rate: 0.0001
  trained_ckpt: checkpoints/best.pth

agent2:
  count: 1
  agent_class: src.agents.astar_agent.AStarAgent
  colors_map: assets/csv_files/colors_map.csv
  targets_map: assets/csv_files/targets_map.csv
  num_robots: 2
  maximum_battery: null

